### ISSUE TITLE
Release assets for v0.0.9

### ISSUE THREAD

**Issue by suzuki-shunsuke** [sheepla/qiitaz#8]
Thank you for your great project.

I found there is no asset for v0.0.9.

https://github.com/sheepla/qiitaz/releases/tag/v0.0.9

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13323303/166398253-1b001cd5-8a32-42b2-ac44-245b381ca7c1.png">

On the other hand, there are assets for other versions.

https://github.com/sheepla/qiitaz/releases/tag/v0.0.8

<img width="800" alt="image" src="https://user-images.githubusercontent.com/13323303/166398360-84488802-4392-41b3-a982-70c23cc07ebe.png">

Could you release assets for v0.0.9?

## Related issues

* https://github.com/aquaproj/aqua-registry/issues/3293

**Comment by suzuki-shunsuke** [comment]
Release job for v0.0.9: https://github.com/sheepla/qiitaz/runs/6245127463?check_suite_focus=true

```
• publishing       
      • scm releases     
         • creating or updating release repo=sheepla/qiitaz tag=v0.0.9
         • uploading to release      file=dist/checksums.txt name=checksums.txt
         • uploading to release      file=dist/qiitaz_0.0.9_Darwin_arm64.tar.gz name=qiitaz_0.0.9_Darwin_arm64.tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Windows_i386.tar.gz name=qiitaz_0.0.9_Windows_i386.tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Darwin_x86_64.tar.gz name=qiitaz_0.0.9_Darwin_x86_64.tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Linux_i386.tar.gz name=qiitaz_0.0.9_Linux_i386.tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Linux_arm64.tar.gz name=qiitaz_0.0.9_Linux_arm[64](https://github.com/sheepla/qiitaz/runs/6245127463?check_suite_focus=true#step:4:64).tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Linux_x86_64.tar.gz name=qiitaz_0.0.9_Linux_x86_64.tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Windows_x86_64.tar.gz name=qiitaz_0.0.9_Windows_x86_64.tar.gz
         • uploading to release      file=dist/qiitaz_0.0.9_Windows_arm64.tar.gz name=qiitaz_0.0.9_Windows_arm64.tar.gz
```

It seems that assets were released by goreleaser properly, but there is no asset for v0.0.9.
It looks strange.

**Comment by sheepla** [comment]
Thank you for finding it! it's strange...

**Comment by sheepla** [comment]
Ah, maybe it's because I removed the v0.0.9 release and released it again. Probably the normal flow should be successful in releasing the asset. It was successful on [v0.1.0](https://github.com/sheepla/qiitaz/releases/tag/v0.1.0).

**Comment by suzuki-shunsuke** [comment]
Oh, I see. Thank you.
I've confirmed that this issue has been solved.

**Comment by sheepla** [comment]
Thank you for your report!
